language: node_js
group: travis_latest
sudo: false

node_js:
  - stable
  - lts/carbon

services:
  - mongodb

cache:
  directories:
    - node_modules

before_cache: rm -rf node_modules/.cache

stages:
  - Test
  - name: &deployStage Deploy
    if: tag IS present

after_success: cat ./coverage/lcov.info | coveralls

jobs:
  include:
    - stage: *deployStage
      node_js: stable
      env:
        - DEPLOY=1
      cache: false
      services: []
      install: []
      script: []
      after_success: []
      before_deploy:
        - node ./set-badges-branch.js
      deploy:
        - provider: npm
          on:
            tags: true
          skip_cleanup: true
          email: a.molcanovas@gmail.com
          api_key:
            secure: "WT+szT01JIPfjJsY1We2bLGeDA2QnHUY8OfJR8SzVXIDJqvxDwoyX5C+dFQtoqgRgv97ZEZctGGptwBJiUdc0XjEhMGUrouAZLAsM7dUuz21nn7TyMEmz/Rg8m3xPwPDpxQEbiSqtJYDulqD367tMrCq++ALyeF8x8JxZkTvaHSbX4u+DsweSga1pEm0SV5MQN7zh0PINQX0f57cZnP01LVcTaZ5ZhNjVbR2RTs+zcpzPhnJ5Yvowrkk+ITo+oj+cRploe73mrB+EAzWdOgoDSYZvmEWRvtqGxetAgSYscwvR2eCAaUQbdjSil9ljL6uOwVpRAZ367mqDwpCVxwDPew6FXYBPqh1xgEQA8675cst00MCwxvZuOpAfPKxO2V58Canl90tNzipNHHy8PyYj9fwEcy1lxQ6anwXAovEWp5JxF8PYUZmlEwfxoZq4abqf/FPFd6YzemZyiUjm2YSHALWCMvMtsXswuTpTb92bUayiZcrS7F54jJGG7VpOgNg48ijcIjA8UQYaSdbVxpyvaahQtHS9nIk++JgUq5MYF9yDFay/KZwdP90k3TlzuRmquk3WiDJ5KgftJs7IY8nW8+UJ48pS5AlOqBMN3UXk/fbL8wfsR0kk+lY7VQM5AFdJUlOBpFXwlQzomuCA/nTXrhcaqndt/GYJve1QSbaOh8="